# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-08 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('reg_no', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
