# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_work', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('donation_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_method', models.CharField(max_length=100)),
                ('procedure', models.TextField()),
                ('contact_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('purpose', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
            ],
        ),
    ]
