# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('cradit', models.FloatField()),
                ('syllabus', models.TextField()),
                ('books', models.TextField()),
                ('sheets', models.CharField(max_length=300)),
                ('software_name', models.CharField(max_length=300)),
                ('software_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Merit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('cgpa', models.FloatField()),
                ('position', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=20)),
                ('reg_no', models.CharField(max_length=20)),
                ('batch', models.PositiveIntegerField()),
                ('height_inch', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('contact_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assi_Professor'), ('Associate Professor', 'Asso_Professor'), ('Professor', 'Professor')], default='Lecturer', max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('select from below', 'select from below')], default='select from below', max_length=20)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
