# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20171207_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='CSE_BRUR/static/images/study/teacher'),
        ),
    ]
