# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=20)),
                ('archive_category', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cse_club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_member', models.CharField(max_length=100)),
                ('club_designation', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('banner_photo', models.ImageField(upload_to='')),
                ('event_category', models.CharField(max_length=100)),
                ('event_schedule', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Game_achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achivement_title', models.CharField(max_length=100)),
                ('achivement_description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('batch', models.PositiveIntegerField()),
                ('player_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achivement', models.CharField(max_length=100)),
            ],
        ),
    ]
