# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inovation_type', models.CharField(choices=[('Thesis', 'Thesis'), ('Project', 'Project'), ('other inovation', 'other inovation')], default='Thesis', max_length=20)),
                ('inovation_title', models.CharField(max_length=100)),
                ('inovation_description', models.TextField()),
                ('id_no', models.CharField(max_length=20)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('publication', models.URLField()),
            ],
        ),
    ]
